language: php

matrix:
  include:
    - env: TYPE=coverage
      php: 5.6
    - env: TYPE=UNIT;
      php: 5.5
    - env: TYPE=UNIT; PHPUNIT=4.8.*
      php: hhvm

script:
  - bash ./tests/ci/run-tests.sh

after_success:
  - bash ./tests/ci/upload-coverage-report.sh
